services:
  db:
    image: postgres:16.4
    platform: linux/amd64
    container_name: polls_dev_db
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - polls-database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gfgf1962
      POSTGRES_DB: polls
    ports:
      - "5432:5432"

  web:
    container_name: polls_dev_web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=kursach.settings
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    build: .
    container_name: polls_dev_celery
    command: >
      bash -c 'celery -A kursach worker -P threads && celery -A kursach beat --loglevel=info'
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    container_name: polls_dev_redis
    environment:
      - DJANGO_SETTINGS_MODULE=kursach.settings
    ports:
      - "6379:6379"
    depends_on:
      - db

  mailhog:
    container_name: polls_dev_mailhog
    image: mailhog/mailhog
    command: bash -c "./MailHog.exe"
    environment:
      - DJANGO_SETTINGS_MODULE=kursach.settings
    ports:
      - "8025:8025"

volumes:
  polls-database: