services:
  web:
    &WEB
    container_name: polls_dev_web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=kursach.settings
      - DATABASE_HOST=host.docker.internal
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - ./:/app
    ports:
      - 8000:8000

  celery:
    <<: *WEB
    container_name: polls_dev_celery
    ports: []
    command: >
      bash -c 'celery -A kursach worker -P threads'
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: polls_dev_redis
    environment:
      - DJANGO_SETTINGS_MODULE=kursach.settings
    ports:
      - 6379:6379

  celery_beat:
    <<: *WEB
    container_name: polls_dev_celerybeat
    ports: []
    command:  >
      bash -c 'celery -A kursach beat -l info'
    depends_on:
      - redis

  mailhog:
    container_name: polls_dev_mailhog
    image: mailhog/mailhog
    environment:
      - DJANGO_SETTINGS_MODULE=kursach.settings
    ports:
      - "8025:8025"