# Generated by Django 5.1.1 on 2024-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='usefull',
            field=models.BooleanField(default=False),
        ),
    ]
