# Generated by Django 5.1.1 on 2024-12-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_answer_usefull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='usefull',
        ),
    ]
