# Generated by Django 5.1.1 on 2024-12-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_answer_usefull'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='usefull',
            field=models.BooleanField(default=False),
        ),
    ]
